### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by GetSimpleCMS-CE** [GetSimpleCMS-CE/GetSimpleCMS-CE#3]
### Ideas / Enhancements / Updates
------------------------
- [x] Replaced **fancybox**
- [ ] Update **Jquery**
- [ ] Update **ckEditor**
- [x] Removed obsolete **Uploadify**
- [x] Removed non-functioning **Jcrop**
- [x] Add **FontAwesome** to core ?
- [ ] Fix "Forgot your password"
- [ ] Add **2FA** (core/plugin)
- [ ] Add **SMTP** for Admin Control Panel
